### ISSUE TITLE
Segfault when adding or duplicating Polyscope

### ISSUE THREAD

**Issue by joefiorini** [jhoar/AmalgamatedHarmonics#53]
@jhoar When I attempt to add Polyscope to a patch it crashes Rack with a segfault. When I go back into Rack and try again it works. But if I try to duplicate it with Ctrl+d it will crash Rack again. It may be related to #50 but it looks like that error was on Windows not Linux. I did notice that you had fixed #50 but the release hasn't been published to the library. I'll try building from source later to see if it fixes my issue. In the meantime here's my backtrace:

```
(gdb) backtrace 
#0  0x00007fffa8db87d9 in PolyScopeDisplay::draw(rack::widget::Widget::DrawArgs const&) () from /home/joe/.Rack2/plugins/AmalgamatedHarmonics/plugin.so
#1  0x00007ffff73dca54 in rack::widget::Widget::drawChild(rack::widget::Widget*, rack::widget::Widget::DrawArgs const&, int) () from ./libRack.so
#2  0x00007ffff73dcb8c in rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&) () from ./libRack.so
#3  0x00007ffff73b2cb5 in rack::app::ModuleWidget::draw(rack::widget::Widget::DrawArgs const&) () from ./libRack.so
#4  0x00007ffff73dca54 in rack::widget::Widget::drawChild(rack::widget::Widget*, rack::widget::Widget::DrawArgs const&, int) () from ./libRack.so
#5  0x00007ffff73dcb8c in rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&) () from ./libRack.so
#6  0x00007ffff73dca54 in rack::widget::Widget::drawChild(rack::widget::Widget*, rack::widget::Widget::DrawArgs const&, int) () from ./libRack.so
#7  0x00007ffff73dcb8c in rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&) () from ./libRack.so
#8  0x00007ffff73c0642 in rack::app::RackWidget::draw(rack::widget::Widget::DrawArgs const&) () from ./libRack.so
#9  0x00007ffff73dca54 in rack::widget::Widget::drawChild(rack::widget::Widget*, rack::widget::Widget::DrawArgs const&, int) () from ./libRack.so
#10 0x00007ffff73dcb8c in rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&) () from ./libRack.so
#11 0x00007ffff73da20c in rack::widget::ZoomWidget::draw(rack::widget::Widget::DrawArgs const&) () from ./libRack.so
#12 0x00007ffff73dca54 in rack::widget::Widget::drawChild(rack::widget::Widget*, rack::widget::Widget::DrawArgs const&, int) () from ./libRack.so
#13 0x00007ffff73dcb8c in rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&) () from ./libRack.so
#14 0x00007ffff73dca54 in rack::widget::Widget::drawChild(rack::widget::Widget*, rack::widget::Widget::DrawArgs const&, int) () from ./libRack.so
#15 0x00007ffff73dcb8c in rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&) () from ./libRack.so
#16 0x00007ffff735f844 in rack::ui::ScrollWidget::draw(rack::widget::Widget::DrawArgs const&) () from ./libRack.so
#17 0x00007ffff73dca54 in rack::widget::Widget::drawChild(rack::widget::Widget*, rack::widget::Widget::DrawArgs const&, int) () from ./libRack.so
#18 0x00007ffff73dcb8c in rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&) () from ./libRack.so
#19 0x00007ffff738ae88 in rack::window::Window::step() () from ./libRack.so
#20 0x00007ffff738b0f8 in rack::window::Window::run() () from ./libRack.so
#21 0x000000000040392d in main ()
```

I'm running on Arch Linux with the 5.19.12 kernel.

**Comment by jhoar** [comment]
Closed in 2.0.1
